apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: albumapi-java
spec:
  host:
  port:
    targetPort: 3500
  tls:
    termination: edge
  to:
    kind: Service
    name: albumapi-java
    weight: 100
  wildcardPolicy: None