apiVersion: v1
kind: Secret
metadata:
  annotations:
    openshift.io/display-name: "Album App DB"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: postgresql
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgresql
  name: postgresql
stringData:
  database-name: album
  database-password: album
  database-user: album
  database-url: jdbc:postgresql://postgresql:5432/album
