apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/display-name: "Album App DB"
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: postgresql
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgresql
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
