apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: albumui
      app.kubernetes.io/component: albumui
      app.kubernetes.io/instance: albumui
    name: albumui
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: albumui
      app.kubernetes.io/component: albumui
      app.kubernetes.io/instance: albumui
    name: albumui
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: albumui:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: src
      git:
        uri: https://github.com/akubicharm/containerapps-albumui
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:20-minimal-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 0w4mGAoRYAgEsjGGpDPV
      type: GitHub
    - generic:
        secret: 1CyRIasHVZII_VwVDwoO
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
