apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-albumapi
    app.kubernetes.io/component: blue-albumapi
    app.kubernetes.io/instance: blue-albumapi
  name: blue-albumapi
spec:
  ports:
  - name: 3500-tcp
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    deployment: blue-albumapi
