apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: green-albumapi
    app.kubernetes.io/component: green-albumapi
    app.kubernetes.io/instance: green-albumapi
  name: green-albumapi
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: albumapi:green
  postCommit: {}
  resources: {}
  source:
    contextDir: src
    git:
      uri: https://github.com/akubicharm/containerapps-albumapi-javascript
      ref: green
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:20-minimal-ubi8
        namespace: openshift
    type: Source
  triggers:
    - github:
        secret: eJiHtwShAPMmOiNuIjV3
      type: GitHub
    - generic:
        secret: YHBXYMBMWDCvE075ZjMD
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

