apiVersion: v1
kind: Service
metadata:
  labels:
    app: green-albumapi
    app.kubernetes.io/component: green-albumapi
    app.kubernetes.io/instance: green-albumapi
  name: green-albumapi
spec:
  ports:
  - name: 3500-tcp
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    deployment: green-albumapi
