apiVersion: v1
kind: Service
metadata:
  labels:
    app: albumapi
    app.kubernetes.io/component: albumapi
    app.kubernetes.io/instance: albumapi
  name: albumapi
spec:
  ports:
  - name: 3500-tcp
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    deployment: blue-albumapi
